FIX: 158 - Ensure GTFS and RAPTOR router have the same stop set
naviqore/public-transit-service pull request #159
Opened 2024-12-09 16:29 UTC by munterfi

If a stop occurs in the GTFS schedule, it should be included in RAPTOR, even if no departures are scheduled from that stop. While adding a large number of such stops could negatively impact performance during the generation of transfers at startup, the effect on routing would be minimal since no route scanning occurs from these stops.

When transfers are generated, it could be that connections from or to stops with no trips are available via a footpath / transfer as first or last leg. Currently we are not generating (between stop) transfers when no trip is active on a stop.

Since this issue originates in the GTFS input, we could issue a warning when adding stops with no departures. Ultimately, however, it is the responsibility of the GTFS producer to address this. Our public transit service should handle such cases gracefully but should not attempt to fix the underlying data issue.

**This PR**:
- Adds all stops to RAPTOR, even if they have no departures / stopping trips or transfers.
- Adjust and refactor GtfsToRaptorConverterIT (make tests passing, asserts are checking actual transfer ids or keys, differentiate between same stop transfers and between stop transfers)

@clukas1: This is an alternative to PR #160 to address the issue #158, which I would prefer due to the consistency between the data in the schedule and the router.

2025-01-10 17:49 UTC, munterfi commented
Hi @clukas1, I have implemented what we discussed in the morning: [Only add stops with departures to raptor, catch exceptions from router in service](https://github.com/naviqore/public-transit-service/pull/159/commits/281c420d21cf90eeaaede1f936af0a03162f5d27) and some more:

- Move transfer generation to convert package.
- Pass generators to converter instead of transfers.
- Generator uses a stop collection to build transfers instead of the complete schedule.
- Service catches IllegalArgumentException of raptor router and returns an empty list.
- Introduce GtfsToRaptorTestSchedule to reuse the ManualSchedule.
- Rename isoLines to isolines, be consistent.

There are still open TODOs since we should think about the exception handling in the service.

2025-01-12 14:31 UTC, clukas1 requested changes
Some minor improvements needed, mainly I think we can improve how transfers are added to the raptor builder and I would include the fallback to location routing if no stops with departures are included in the request.

2025-01-12 14:31 UTC, clukas1 commented on src/main/java/ch/naviqore/service/gtfs/raptor/convert/GtfsToRaptorConverter.java
> +    private void createAndAddAdditionalTransfers() {
I thought we had removed than in a prior issue but because addTransfer() adds transfers to a map, the check with GTFS stops and separate map for generated transfers is no longer necessary.

We can simply add all generated transfers, as long as the lowest priority transfer generator creates its transfers first.

2025-01-12 14:31 UTC, clukas1 commented on src/test/java/ch/naviqore/service/gtfs/raptor/convert/GtfsToRaptorConverterIT.java
> +            RaptorAlgorithm raptor = mapper.run();
would rename mapper to converter

2025-01-12 14:31 UTC, clukas1 commented on src/test/java/ch/naviqore/service/gtfs/raptor/GtfsRaptorServiceIT.java
> +                void source_arrival() throws ConnectionRoutingException, StopNotFoundException {
why snake case? same for some tests above?

2025-01-12 14:31 UTC, clukas1 commented on src/main/java/ch/naviqore/service/gtfs/raptor/GtfsRaptorService.java
> +            return List.of();
TODO: Add fallback on location routing?

2025-01-12 14:31 UTC, clukas1 commented on src/main/java/ch/naviqore/service/gtfs/raptor/GtfsRaptorService.java
> +            log.debug(e.getMessage());
Maybe also fallback to location isolines?

2025-01-12 22:12 UTC, clukas1 commented on src/main/java/ch/naviqore/service/gtfs/raptor/GtfsRaptorService.java
> +            //  throw new ConnectionRoutingException(e);
Partially implemented in 68f3c9d and 87b1bd7

2025-01-12 22:13 UTC, clukas1 commented on src/main/java/ch/naviqore/service/gtfs/raptor/convert/GtfsToRaptorConverter.java
> +    private void createAndAddAdditionalTransfers() {
Simplified in 26f29a6 and added another test 036b5de

2025-01-12 22:13 UTC, clukas1 commented on src/test/java/ch/naviqore/service/gtfs/raptor/convert/GtfsToRaptorConverterIT.java
> +            RaptorAlgorithm raptor = mapper.run();
Done in 7755d73

2025-01-13 10:45 UTC, munterfi commented on src/test/java/ch/naviqore/service/gtfs/raptor/GtfsRaptorServiceIT.java
> +                void source_arrival() throws ConnectionRoutingException, StopNotFoundException {
Changed in 20eec36edf7302aca54d65770e5afa25838f234d

2025-01-13 16:37 UTC, munterfi commented
Thanks @clukas1, nice work! All changes are good from my side.

Currently I am trying to refactor the service using the template method pattern on a separate branch: https://github.com/naviqore/public-transit-service/tree/concept/refactor-service

I will open a PR into this branch as soon as I am ready.

2025-01-13 22:12 UTC, clukas1 commented
@munterfi Changes here look good, should I approve this PR or should we wait for the template method pattern PR (including correct InvalidStopException handling)? 

Regarding your new branch, I've had a look and added a commit mainly with comments but also some suggestions how I think we can handle Invalid Stop Exceptions by falling back to location routing in ebea0b0.

2025-01-13 22:18 UTC, clukas1 commented on src/main/java/ch/naviqore/service/gtfs/raptor/GtfsRaptorService.java
> +            log.debug(e.getMessage());
See my suggestion in ebea0b0, I think we using the template method pattern this can actually be handled fairly nicely. However, I think we should add some connection post processing to add the source stop to the first/lastMile walk etc. and also add post processing with the walk calculator if first/lastMile walks are followed by a walk transfer as first or last leg in the raptor connection.

2025-01-14 10:08 UTC, munterfi commented
Hi @clukas, I think we can merge this PR, since it fixes the original issue.

The new branch is mainly a refactoring to simplify the fallback solution with the location search.

2025-01-14 22:02 UTC, clukas1 approved these changes

2025-01-14 22:02 UTC, merged